version: "3.9"

services:
  denotask:
    container_name: denotask
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .env:/app/.env:ro
      - ./examples:/app/examples:rw

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
